ALTER TYPE "AuditEventType" ADD VALUE IF NOT EXISTS 'DOCUMENT_ARTIFACT_GENERATED';
ALTER TYPE "AuditEventType" ADD VALUE IF NOT EXISTS 'DOCUMENT_ARTIFACT_GENERATION_FAILED';

ALTER TABLE "ProcessDocument"
  ADD COLUMN IF NOT EXISTS "artifactChecksum" TEXT,
  ADD COLUMN IF NOT EXISTS "artifactGeneratedAt" TIMESTAMP(3);
