export enum DocumentType {
  SUPERVISOR_EVALUATION = 'SUPERVISOR_EVALUATION',
  SELF_EVALUATION = 'SELF_EVALUATION',
  CESAD_OPINION = 'CESAD_OPINION',
  HOMOLOGATION_RECORD = 'HOMOLOGATION_RECORD',
  RESULT_NOTIFICATION = 'RESULT_NOTIFICATION',
  ACKNOWLEDGEMENT_RECORD = 'ACKNOWLEDGEMENT_RECORD',
  ORDINANCE = 'ORDINANCE',
}
