export enum DocumentStatus {
  DRAFT = 'DRAFT',
  CONSOLIDATED = 'CONSOLIDATED',
  READY_FOR_SIGNATURE = 'READY_FOR_SIGNATURE',
  SIGNED = 'SIGNED',
  INVALIDATED_OR_SUPERSEDED = 'INVALIDATED_OR_SUPERSEDED',
}
