export enum ProcessStatus {
  EM_AVALIACAO = 'EM_AVALIACAO',
  AGUARDANDO_ASSINATURA = 'AGUARDANDO_ASSINATURA',
  ASSINADO = 'ASSINADO',
  EM_ANALISE_CESAD = 'EM_ANALISE_CESAD',
  PARECER_EMITIDO = 'PARECER_EMITIDO',
  HOMOLOGADO = 'HOMOLOGADO',
  NOTIFICADO = 'NOTIFICADO',
  CIENTE = 'CIENTE',
  ENCERRADO = 'ENCERRADO',
}
