export enum UserRole {
  INTERN_SERVER = 'INTERN_SERVER',
  IMMEDIATE_SUPERVISOR = 'IMMEDIATE_SUPERVISOR',
  CESAD_MEMBER = 'CESAD_MEMBER',
  HOMOLOGATION_AUTHORITY = 'HOMOLOGATION_AUTHORITY',
  ADMIN = 'ADMIN',
}
